packages:
  - packages/*
  - tools/dbpatch
  - app/
  # Examples temporarily excluded (some depend on archived packages)
  # - examples/*
  # Archived packages (not used in desktop app)
  # - archived-packages/*

onlyBuiltDependencies:
  - esbuild
  - nx
  - sharp
  - tree-sitter
  - tree-sitter-haskell
